# Generated by Django 5.2.17 on 2026-08-25 03:58

import django.core.validators
from django.db import migrations, models


def sembrar_limitador(apps, schema_editor):
    """
    Crea la cubeta de fichas para Decolecta.

    capacidad = 3 (ráfaga) y tasa = 6/s (sostenido): el peor segundo posible
    es 3 + 6 = 9 consultas, con 1 de margen bajo el tope de 10/s del plan
    actual.

    Si contratan un plan mayor, se cambia DESDE EL ADMIN de Django
    (Voluntarios > Limitadores de API), sin tocar código ni redesplegar.
    Regla al calibrar: capacidad + tasa < tope de la API.
    """
    LimitadorApi = apps.get_model("voluntarios", "LimitadorApi")
    LimitadorApi.objects.update_or_create(
        clave="decolecta",
        defaults={"tokens": 3.0, "capacidad": 3.0, "tasa": 6.0},
    )


def borrar_limitador(apps, schema_editor):
    LimitadorApi = apps.get_model("voluntarios", "LimitadorApi")
    LimitadorApi.objects.filter(clave="decolecta").delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitadorApi',
            fields=[
                ('clave', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('tokens', models.FloatField(default=3.0)),
                ('capacidad', models.FloatField(default=3.0, help_text='Ráfaga máxima')),
                ('tasa', models.FloatField(default=6.0, help_text='Fichas por segundo (sostenido)')),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Limitador de API',
                'verbose_name_plural': 'Limitadores de API',
                'db_table': 'voluntarios_limitador_api',
            },
        ),
        migrations.CreateModel(
            name='ConsultaReniec',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=120)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(blank=True, max_length=80)),
                ('nombre_completo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Consulta a RENIEC',
                'verbose_name_plural': 'Consultas a RENIEC',
                'db_table': 'voluntarios_consulta_reniec',
                'indexes': [models.Index(fields=['updated_at'], name='reniec_consultado_idx')],
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(editable=False, max_length=12, unique=True)),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'El DNI debe tener 8 dígitos.')])),
                ('nombres', models.CharField(max_length=120)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(blank=True, max_length=80)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^9\\d{8}$', 'El celular debe tener 9 dígitos y empezar con 9.')])),
                ('acepta_whatsapp', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('preinscrito', 'Preinscrito'), ('confirmado', 'Confirmado'), ('baja', 'Baja')], default='preinscrito', max_length=20)),
                ('origen', models.CharField(default='web_unete', max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Voluntario',
                'verbose_name_plural': 'Voluntarios',
                'db_table': 'voluntarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='voluntario_creado_idx'), models.Index(fields=['estado'], name='voluntario_estado_idx')],
            },
        ),
            migrations.RunPython(sembrar_limitador, borrar_limitador),
        # Secuencia para los códigos correlativos (PRG-0001, PRG-0002, …).
        # Va en la base y no en Python porque nextval() es atómico: nunca
        # entrega el mismo número a dos workers que insertan a la vez.
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS voluntarios_codigo_seq START WITH 1;",
            reverse_sql="DROP SEQUENCE IF EXISTS voluntarios_codigo_seq;",
        ),
    ]
