# Generated by Django 5.2.17 on 2026-08-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='voluntario/'),
        ),
    ]
