# Generated by Django 5.2.17 on 2026-08-31 13:16

import app.voluntarios.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        ('voluntarios', '0002_voluntario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='rol_afiliado',
            field=models.ForeignKey(db_column='id_rol_afiliado', default=app.voluntarios.models._rol_afiliado_default, on_delete=django.db.models.deletion.PROTECT, related_name='voluntarios', to='asistencia.rolafiliado'),
        ),
    ]
