# Generated by Django 5.2.17 on 2026-08-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0003_voluntario_rol_afiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
