# Generated by Django 5.2.17 on 2026-08-17 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'ordering': ['orden', 'id_candidato'], 'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='apellido',
            new_name='apellido_paterno',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='biografia',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AlterUniqueTogether(
            name='candidato',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='candidato',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidato',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cargo',
            field=models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='candidatos.cargo'),
        ),
    ]
