# Generated by Django 5.2.17 on 2026-10-01 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalVotacion',
            fields=[
                ('id_local', models.IntegerField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=50)),
                ('nombre_local', models.CharField(max_length=150)),
                ('direccion_local', models.CharField(blank=True, max_length=200, null=True)),
                ('cant_mesas', models.PositiveIntegerField()),
                ('electores_regional', models.PositiveIntegerField()),
                ('extranjeros_inscritos', models.PositiveIntegerField(default=0)),
                ('electores_municipal', models.PositiveIntegerField()),
                ('localidades_msi', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Locales de Votación',
                'db_table': 'local_votacion',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_partido', models.CharField(max_length=150, unique=True)),
                ('categoria', models.CharField(default='PARTIDO', max_length=10)),
            ],
            options={
                'db_table': 'partido',
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id_voto', models.AutoField(primary_key=True, serialize=False)),
                ('nro_mesa', models.PositiveIntegerField()),
                ('tipo_eleccion', models.CharField(choices=[('REGIONAL', 'REGIONAL'), ('PROVINCIAL', 'PROVINCIAL'), ('DISTRITAL', 'DISTRITAL')], max_length=20)),
                ('cant_voto', models.PositiveIntegerField(default=0)),
                ('local', models.ForeignKey(db_column='id_local', on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='escrutinio.localvotacion')),
                ('partido', models.ForeignKey(db_column='id_partido', on_delete=django.db.models.deletion.CASCADE, to='escrutinio.partido')),
            ],
            options={
                'db_table': 'voto',
                'unique_together': {('local', 'nro_mesa', 'tipo_eleccion', 'partido')},
            },
        ),
    ]
