# Generated by Django 5.2.17 on 2026-10-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrutinio', '0002_alter_voto_nro_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='tipo_eleccion',
            field=models.CharField(choices=[('REGIONAL', 'Regional'), ('CONSEJERO', 'Consejero Regional'), ('PROVINCIAL', 'Provincial'), ('DISTRITAL', 'Distrital')], max_length=20),
        ),
    ]
