# Generated by Django 5.2.17 on 2026-08-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
