# Generated by Django 5.2.17 on 2026-08-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('imagen', models.ImageField(upload_to='carrusel/')),
                ('texto_boton', models.CharField(blank=True, max_length=100)),
                ('url_boton', models.URLField(blank=True, max_length=500)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Carrusel',
                'verbose_name_plural': 'Carrusel',
                'db_table': 'carrusel',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de publicación',
                'verbose_name_plural': 'Categorías de publicación',
                'db_table': 'categorias_publicacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_partido', models.CharField(max_length=255)),
                ('siglas', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('descripcion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True, max_length=500)),
                ('instagram', models.URLField(blank=True, max_length=500)),
                ('tiktok', models.URLField(blank=True, max_length=500)),
                ('youtube', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
                'db_table': 'configuracion_sitio',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('tipo_archivo', models.CharField(blank=True, max_length=50)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etiqueta', models.CharField(max_length=100)),
                ('valor', models.PositiveIntegerField()),
                ('prefijo', models.CharField(blank=True, max_length=10)),
                ('sufijo', models.CharField(blank=True, max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
                'db_table': 'estadisticas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Pregunta frecuente',
                'verbose_name_plural': 'Preguntas frecuentes',
                'db_table': 'faqs',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=30)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='multimedia/')),
                ('url_externa', models.URLField(blank=True, max_length=500, null=True)),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to='multimedia/miniaturas/')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Multimedia',
                'verbose_name_plural': 'Multimedia',
                'db_table': 'multimedia',
                'ordering': ['orden', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='propuestas/')),
                ('eje', models.CharField(choices=[('educacion', 'Educación'), ('salud', 'Salud'), ('seguridad', 'Seguridad'), ('economia', 'Economía'), ('infraestructura', 'Infraestructura'), ('agricultura', 'Agricultura'), ('innovacion', 'Innovación'), ('desarrollo_regional', 'Desarrollo Regional')], max_length=30)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
                'db_table': 'propuestas',
                'ordering': ['orden', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('resumen', models.TextField(blank=True)),
                ('contenido', models.TextField()),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='publicaciones/portadas/')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=30)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'db_table': 'publicaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
