# Generated by Django 5.2.17 on 2026-08-18 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multimedia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='cms.categoriapublicacion'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['estado', '-fecha_publicacion'], name='pub_estado_fecha_idx'),
        ),
    ]
