# Generated by Django 5.2.17 on 2026-08-17 04:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrusel',
            options={'ordering': ['orden'], 'verbose_name': 'Carrusel', 'verbose_name_plural': 'Carrusel'},
        ),
        migrations.AlterModelOptions(
            name='categoriapublicacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría de publicación', 'verbose_name_plural': 'Categorías de publicación'},
        ),
        migrations.AlterModelOptions(
            name='configuracionsitio',
            options={'verbose_name': 'Configuración del sitio', 'verbose_name_plural': 'Configuración del sitio'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-created_at'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='multimedia',
            options={'ordering': ['orden', '-created_at'], 'verbose_name': 'Multimedia', 'verbose_name_plural': 'Multimedia'},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.RenameField(
            model_name='configuracionsitio',
            old_name='valor',
            new_name='nombre_partido',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='carrusel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='carrusel',
            name='multimedia',
        ),
        migrations.RemoveField(
            model_name='carrusel',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='categoriapublicacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='categoriapublicacion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='url_externa',
        ),
        migrations.RemoveField(
            model_name='multimedia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='multimedia',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='id',
        ),
        migrations.AddField(
            model_name='carrusel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrusel',
            name='id_carrusel',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='imagen',
            field=models.ImageField(default='', upload_to='carrusel/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrusel',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='texto_boton',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='url_boton',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='categoriapublicacion',
            name='id_categoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='categoriapublicacion',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='correo',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='facebook',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='configuracion/'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='id_configuracion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='instagram',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='configuracion/'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='siglas',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='tiktok',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='youtube',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='documento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='id_documento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_archivo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documento',
            name='titulo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multimedia',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='id_multimedia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='multimedia/miniaturas/'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multimedia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='id_publicacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/portadas/'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='resumen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='multimedia/'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=30),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='url_externa',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='cms.categoriapublicacion'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=30),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='carrusel',
            table='carrusel',
        ),
    ]
