# Generated by Django 5.2.17 on 2026-08-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
