# Generated by Django 5.2.17 on 2026-08-16 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('codigo_carnet', models.CharField(max_length=50, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='afiliados/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afiliados_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Afiliado',
                'verbose_name_plural': 'Afiliados',
                'db_table': 'afiliados',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
    ]
