# Generated by Django 5.2.17 on 2026-08-31 13:16

import django.db.models.deletion
from django.db import migrations, models


def sembrar_roles_afiliado(apps, schema_editor):
    RolAfiliado = apps.get_model("asistencia", "RolAfiliado")
    for nombre in ("afiliado", "organizador", "simpatizante"):
        RolAfiliado.objects.get_or_create(rol_name=nombre)


def borrar_roles_afiliado(apps, schema_editor):
    RolAfiliado = apps.get_model("asistencia", "RolAfiliado")
    RolAfiliado.objects.filter(
        rol_name__in=("afiliado", "organizador", "simpatizante")
    ).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voluntarios', '0002_voluntario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(blank=True, max_length=40)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RolAfiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol de afiliado',
                'verbose_name_plural': 'Roles de afiliado',
                'db_table': 'afiliado_rol',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('justificado', 'Justificado'), ('eliminado', 'Eliminado')], default='presente', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.actividad')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'voluntarios_asistencia',
            },
        ),
        migrations.RunPython(sembrar_roles_afiliado, borrar_roles_afiliado),
    ]
